name: Deploy Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependências de build
        run: sudo apt-get update && sudo apt-get install -y build-essential python3-dev

      - name: Instalar dependências
        run: pip install -r requirements.txt -t app

      - name: Preparar pacote para Lambda
        run: |
          cp lambda_function.py app/
          cp -r src app/
          # O requirements.txt não será copiado para app, pois as libs já estão instaladas
          cd app
          zip -r ../function.zip .
          cd ..

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          zip_file: function.zip
